express:
  port: 3002

auth:
  username: 'admin'
  password: 'password'

devices:
  marantz:
    server: '192.168.10.176'
    buttons:
      power:
        on: 'PutZone_OnOff/ON'
        off: 'PutZone_OnOff/OFF'
      aux2: 'PutZone_InputFunction/AUX2'
      bluray: 'PutZone_InputFunction/BD'
      game: 'PutZone_InputFunction/GAME'
      media: 'PutZone_InputFunction/MPLAY'
      mute: 'PutVolumeMute/on'
      volDown: 'PutMasterVolumeBtn/<'
      volPreset: 'PutMasterVolumeSet/-20.0'
      volUp: 'PutMasterVolumeBtn/>'

commands:
  tv:
    on: 'irsend SEND_ONCE Benq850 ON'
    off: 'irsend SEND_ONCE Benq850 OFF'
  ps5:
